// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgPZU_7MtKxBdJdpnqlQWHOorcitN_dY',
    appId: '1:440786686004:web:d2b31a6085e66e3c9bfa61',
    messagingSenderId: '440786686004',
    projectId: 'flutterfeedback-f4e2d',
    authDomain: 'flutterfeedback-f4e2d.firebaseapp.com',
    storageBucket: 'flutterfeedback-f4e2d.appspot.com',
    measurementId: 'G-RMY5Z37W0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSFtM9VJrZKNLa425DCVAQ_vRiqU17-A',
    appId: '1:440786686004:android:68180480f14600d39bfa61',
    messagingSenderId: '440786686004',
    projectId: 'flutterfeedback-f4e2d',
    storageBucket: 'flutterfeedback-f4e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmkX_O7pdwBlVup_9-66F7ae13IWUIoM',
    appId: '1:440786686004:ios:17122883f9a1fde39bfa61',
    messagingSenderId: '440786686004',
    projectId: 'flutterfeedback-f4e2d',
    storageBucket: 'flutterfeedback-f4e2d.appspot.com',
    iosClientId: '440786686004-i60koaojbmpc13eugkqkl8hp0goo5nk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmkX_O7pdwBlVup_9-66F7ae13IWUIoM',
    appId: '1:440786686004:ios:17122883f9a1fde39bfa61',
    messagingSenderId: '440786686004',
    projectId: 'flutterfeedback-f4e2d',
    storageBucket: 'flutterfeedback-f4e2d.appspot.com',
    iosClientId: '440786686004-i60koaojbmpc13eugkqkl8hp0goo5nk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );
}
